# Generated by Django 5.0.2 on 2024-10-16 16:43

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Dailyreport",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "tokki_naiyo",
                    models.TextField(blank=True, max_length=1000, verbose_name="特記内容"),
                ),
                (
                    "tsusho_unagashi",
                    models.BooleanField(default=False, verbose_name="通所促し"),
                ),
                (
                    "taityomen",
                    models.CharField(blank=True, max_length=15, verbose_name="体調面"),
                ),
                (
                    "haisetsu",
                    models.IntegerField(
                        blank=True,
                        choices=[(0, "未"), (1, "小"), (2, "中"), (3, "大")],
                        null=True,
                        verbose_name="排泄",
                    ),
                ),
                (
                    "kenon_1",
                    models.CharField(blank=True, max_length=30, verbose_name="検温１"),
                ),
                (
                    "kenon_2",
                    models.CharField(blank=True, max_length=30, verbose_name="検温２"),
                ),
                (
                    "chushoku",
                    models.CharField(blank=True, max_length=30, verbose_name="昼食"),
                ),
                (
                    "suibun",
                    models.CharField(blank=True, max_length=30, verbose_name="水分"),
                ),
                (
                    "sogei_1",
                    models.CharField(blank=True, max_length=30, verbose_name="送迎 行"),
                ),
                (
                    "sogei_2",
                    models.CharField(blank=True, max_length=30, verbose_name="送迎 帰"),
                ),
                (
                    "shozai_jikan_1",
                    models.TimeField(blank=True, null=True, verbose_name="所在 時間１"),
                ),
                (
                    "shozai_jikan_2",
                    models.TimeField(blank=True, null=True, verbose_name="所在 時間２"),
                ),
                (
                    "denwa_shien_1",
                    models.BooleanField(default=False, verbose_name="電話支援１"),
                ),
                (
                    "denwa_shien_2",
                    models.BooleanField(default=False, verbose_name="電話支援２"),
                ),
                ("kesseki", models.BooleanField(default=False, verbose_name="欠席")),
                (
                    "kesseki_kasan",
                    models.BooleanField(default=False, verbose_name="欠席加算"),
                ),
                (
                    "toroku_date",
                    models.DateTimeField(
                        default=django.utils.timezone.localtime, verbose_name="登録日付"
                    ),
                ),
                (
                    "update_date",
                    models.DateTimeField(auto_now=True, verbose_name="更新日"),
                ),
            ],
            options={"verbose_name_plural": "日中報告内容",},
        ),
        migrations.CreateModel(
            name="Inspection",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "syobo_keirokakunin",
                    models.BooleanField(default=False, verbose_name="避難経路確認"),
                ),
                (
                    "syobo_syobosetsubi",
                    models.BooleanField(default=False, verbose_name="消防設備"),
                ),
                (
                    "syobo_syokakisecchi",
                    models.BooleanField(default=False, verbose_name="消火器設置"),
                ),
                (
                    "syobo_kakikakunin",
                    models.BooleanField(default=False, verbose_name="火器確認"),
                ),
                (
                    "syobo_suikounetsu",
                    models.BooleanField(default=False, verbose_name="水光熱"),
                ),
                (
                    "tokki_naiyo",
                    models.TextField(blank=True, max_length=1000, verbose_name="特記内容"),
                ),
                (
                    "toroku_date",
                    models.DateTimeField(
                        default=django.utils.timezone.localtime, verbose_name="登録日付"
                    ),
                ),
                (
                    "update_date",
                    models.DateTimeField(auto_now=True, verbose_name="更新日"),
                ),
            ],
            options={"verbose_name_plural": "消防点検情報",},
        ),
        migrations.CreateModel(
            name="Visitor",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("tsusho_name", models.CharField(max_length=30, verbose_name="通所者氏名")),
                ("tsusho_seinengappi", models.DateField(verbose_name="通所者生年月日")),
                (
                    "tsusho_seibetsu",
                    models.IntegerField(
                        choices=[(0, "未回答"), (1, "男性"), (2, "女性"), (3, "回答しない")],
                        default=0,
                        verbose_name="通所者性別",
                    ),
                ),
                (
                    "tsusho_phone",
                    models.CharField(blank=True, max_length=11, verbose_name="通所者電話番号"),
                ),
                (
                    "tsusho_email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="通所者メールアドレス"
                    ),
                ),
                (
                    "hogo_name",
                    models.CharField(blank=True, max_length=30, verbose_name="保護者氏名"),
                ),
                (
                    "hogo_phone",
                    models.CharField(blank=True, max_length=11, verbose_name="保護者電話番号"),
                ),
                (
                    "hogo_email",
                    models.EmailField(
                        blank=True, max_length=254, verbose_name="保護者メールアドレス"
                    ),
                ),
                (
                    "tokki_naiyo",
                    models.TextField(blank=True, max_length=1000, verbose_name="特記内容"),
                ),
                (
                    "toroku_date",
                    models.DateTimeField(
                        default=django.utils.timezone.localtime, verbose_name="登録日付"
                    ),
                ),
                (
                    "update_date",
                    models.DateTimeField(auto_now=True, verbose_name="更新日"),
                ),
            ],
            options={"verbose_name_plural": "通所者情報",},
        ),
    ]
