# Generated by Django 5.0.2 on 2024-10-23 21:35

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dailyreports", "0003_alter_dailyreport_toroku_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="dailyreport",
            name="haisetsu",
            field=models.IntegerField(
                blank=True,
                choices=[(0, "未"), (1, "小"), (2, "中"), (3, "大")],
                default=0,
                null=True,
                verbose_name="排泄",
            ),
        ),
    ]
