# Generated by Django 5.0.2 on 2024-11-03 15:42

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("dailyreports", "0004_alter_dailyreport_haisetsu"),
    ]

    operations = [
        migrations.AddField(
            model_name="visitor",
            name="is_active",
            field=models.BooleanField(
                default=True,
                help_text="このユーザーがアクティブかどうかを示します。アカウント削除の代わりにこれを選択解除します。",
                verbose_name="アクティブ",
            ),
        ),
    ]
