# Generated by Django 5.0.2 on 2024-10-16 16:43

import django.contrib.auth.validators
import django.core.validators
import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ("auth", "0012_alter_user_first_name_max_length"),
    ]

    operations = [
        migrations.CreateModel(
            name="User",
            fields=[
                (
                    "id",
                    models.AutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("password", models.CharField(max_length=128, verbose_name="パスワード")),
                (
                    "last_login",
                    models.DateTimeField(blank=True, null=True, verbose_name="最終ログイン"),
                ),
                (
                    "is_superuser",
                    models.BooleanField(
                        default=False,
                        help_text="特別な操作なく、このユーザーにすべての権限があることを示します。",
                        verbose_name="スーパーユーザー",
                    ),
                ),
                (
                    "username",
                    models.CharField(
                        error_messages={"unique": "もうすでに存在しているユーザー名です。"},
                        help_text="必須項目。5文字以上50文字以内で、半角英数字と、@/./+/-/_ の記号のみで入力してください。",
                        max_length=50,
                        unique=True,
                        validators=[
                            django.core.validators.MinLengthValidator(5),
                            django.contrib.auth.validators.UnicodeUsernameValidator(),
                        ],
                        verbose_name="ユーザー名",
                    ),
                ),
                (
                    "full_name",
                    models.CharField(blank=True, max_length=150, verbose_name="フルネーム"),
                ),
                (
                    "gender",
                    models.IntegerField(
                        choices=[(0, "未回答"), (1, "男性"), (2, "女性"), (3, "回答しない")],
                        default=0,
                        verbose_name="性別",
                    ),
                ),
                (
                    "birth",
                    models.DateField(
                        default=django.utils.timezone.localdate, verbose_name="生年月日"
                    ),
                ),
                ("on_work", models.BooleanField(default=False, verbose_name="勤務中")),
                (
                    "contract_type",
                    models.IntegerField(
                        choices=[
                            (0, "正社員"),
                            (1, "契約社員"),
                            (2, "アルバイト"),
                            (4, "パート社員"),
                            (5, "派遣社員"),
                            (6, "その他"),
                        ],
                        default=0,
                        verbose_name="雇用形態",
                    ),
                ),
                (
                    "authority",
                    models.IntegerField(
                        choices=[
                            (0, "ゲスト"),
                            (1, "閲覧"),
                            (2, "閲覧作成"),
                            (3, "閲覧作成削除"),
                            (4, "閲覧作成削除管理"),
                        ],
                        default=0,
                        verbose_name="権限",
                    ),
                ),
                (
                    "email",
                    models.EmailField(
                        max_length=254, unique=True, verbose_name="メールアドレス"
                    ),
                ),
                (
                    "phone",
                    models.CharField(
                        blank=True, max_length=11, null=True, verbose_name="電話番号"
                    ),
                ),
                (
                    "introduction",
                    models.TextField(
                        blank=True, max_length=500, null=True, verbose_name="自己紹介"
                    ),
                ),
                (
                    "is_staff",
                    models.BooleanField(
                        default=False,
                        help_text="このユーザーが管理サイトを使用できるかどうかを示します。",
                        verbose_name="管理者権限",
                    ),
                ),
                (
                    "is_active",
                    models.BooleanField(
                        default=True,
                        help_text="このユーザーがアクティブかどうかを示します。アカウント削除の代わりにこれを選択解除します。",
                        verbose_name="アクティブ",
                    ),
                ),
                (
                    "date_joined",
                    models.DateTimeField(
                        default=django.utils.timezone.localtime, verbose_name="ユーザー登録日"
                    ),
                ),
                (
                    "groups",
                    models.ManyToManyField(
                        blank=True,
                        help_text="The groups this user belongs to. A user will get all permissions granted to each of their groups.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.group",
                        verbose_name="groups",
                    ),
                ),
                (
                    "user_permissions",
                    models.ManyToManyField(
                        blank=True,
                        help_text="Specific permissions for this user.",
                        related_name="user_set",
                        related_query_name="user",
                        to="auth.permission",
                        verbose_name="user permissions",
                    ),
                ),
            ],
            options={"abstract": False,},
        ),
    ]
