# Generated by Django 5.0.2 on 2024-10-19 16:51

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registration", "0001_initial"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="user", options={"verbose_name_plural": "ユーザー情報"},
        ),
        migrations.AddField(
            model_name="user",
            name="update_date",
            field=models.DateTimeField(auto_now=True, verbose_name="更新日"),
        ),
        migrations.AlterField(
            model_name="user",
            name="contract_type",
            field=models.IntegerField(
                choices=[
                    (0, "正社員"),
                    (1, "契約社員"),
                    (2, "アルバイト"),
                    (3, "パート社員"),
                    (4, "派遣社員"),
                    (5, "その他"),
                ],
                default=0,
                verbose_name="雇用形態",
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="date_joined",
            field=models.DateTimeField(
                default=django.utils.timezone.localtime, verbose_name="登録日"
            ),
        ),
    ]
