# Generated by Django 5.0.2 on 2024-10-21 22:31

import django.db.models.deletion
import django.utils.timezone
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registration", "0002_alter_user_options_user_update_date_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="AttendanceManagement",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                (
                    "date",
                    models.DateField(
                        default=django.utils.timezone.localdate, verbose_name="日付"
                    ),
                ),
                (
                    "type",
                    models.IntegerField(
                        choices=[(0, "出勤"), (1, "退勤")], default=0, verbose_name="種類"
                    ),
                ),
                (
                    "time_in",
                    models.DateTimeField(blank=True, null=True, verbose_name="時間"),
                ),
                (
                    "toroku_date",
                    models.DateTimeField(
                        default=django.utils.timezone.localtime, verbose_name="登録日"
                    ),
                ),
                (
                    "update_date",
                    models.DateTimeField(auto_now=True, verbose_name="更新日"),
                ),
                (
                    "user",
                    models.ForeignKey(
                        on_delete=django.db.models.deletion.PROTECT,
                        to=settings.AUTH_USER_MODEL,
                        verbose_name="従業員",
                    ),
                ),
            ],
            options={"verbose_name_plural": "勤怠情報",},
        ),
    ]
