# Generated by Django 5.0.2 on 2024-10-21 22:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("registration", "0003_attendancemanagement"),
    ]

    operations = [
        migrations.RenameField(
            model_name="attendancemanagement", old_name="time_in", new_name="time",
        ),
    ]
