# Generated by Django 5.0.2 on 2024-10-22 04:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registration", "0004_rename_time_in_attendancemanagement_time"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attendancemanagement",
            name="time",
            field=models.TimeField(blank=True, null=True, verbose_name="時間"),
        ),
    ]
