# Generated by Django 5.0.2 on 2024-10-23 09:03

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registration", "0005_alter_attendancemanagement_time"),
    ]

    operations = [
        migrations.AddField(
            model_name="attendancemanagement",
            name="biko",
            field=models.CharField(
                blank=True, max_length=30, null=True, verbose_name="備考"
            ),
        ),
    ]
