# Generated by Django 5.0.2 on 2024-10-23 09:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registration", "0006_attendancemanagement_biko"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attendancemanagement",
            name="biko",
            field=models.CharField(
                blank=True, default="", max_length=30, null=True, verbose_name="備考"
            ),
        ),
    ]
