# Generated by Django 5.0.2 on 2024-10-24 10:53

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registration", "0007_alter_attendancemanagement_biko"),
    ]

    operations = [
        migrations.AlterField(
            model_name="attendancemanagement",
            name="update_date",
            field=models.DateTimeField(
                default=django.utils.timezone.localtime, verbose_name="更新日"
            ),
        ),
    ]
