# Generated by Django 5.0.2 on 2024-11-02 12:15

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registration", "0008_alter_attendancemanagement_update_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="full_name",
            field=models.CharField(blank=True, max_length=50, verbose_name="フルネーム"),
        ),
    ]
