# Generated by Django 5.0.2 on 2024-11-03 16:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("registration", "0011_alter_user_username"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="authority",
            field=models.IntegerField(
                choices=[(0, "0"), (1, "1"), (2, "2"), (3, "3"), (4, "ユーザー作成削除")],
                default=0,
                verbose_name="権限",
            ),
        ),
    ]
